FROM debian:latest

MAINTAINER Anders Piniesjö <pugo@pugo.org>

RUN apt-get update && apt-get install -y \
    g++ \
    gcc \
    cmake \
    make \
    git \
    libboost-all-dev \
    libgtest-dev \
    libgmock-dev


